// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuw2W_Xf-GUg630dtmX85JeIGRHm_mWyI',
    appId: '1:524404964921:web:05df48078ccacb32f297e8',
    messagingSenderId: '524404964921',
    projectId: 'cooking-app-e6531',
    authDomain: 'cooking-app-e6531.firebaseapp.com',
    storageBucket: 'cooking-app-e6531.appspot.com',
    measurementId: 'G-JEK3DCV08C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8imfo3o4Ak66KwVMFYHz49CKwBVPG4Y',
    appId: '1:524404964921:android:97a78fc7c891b05df297e8',
    messagingSenderId: '524404964921',
    projectId: 'cooking-app-e6531',
    storageBucket: 'cooking-app-e6531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBHYUhpkaQXuPokX5eQ7ZSNwhgrjkFrs',
    appId: '1:524404964921:ios:032d816e63cbf8eef297e8',
    messagingSenderId: '524404964921',
    projectId: 'cooking-app-e6531',
    storageBucket: 'cooking-app-e6531.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANBHYUhpkaQXuPokX5eQ7ZSNwhgrjkFrs',
    appId: '1:524404964921:ios:032d816e63cbf8eef297e8',
    messagingSenderId: '524404964921',
    projectId: 'cooking-app-e6531',
    storageBucket: 'cooking-app-e6531.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuw2W_Xf-GUg630dtmX85JeIGRHm_mWyI',
    appId: '1:524404964921:web:05d23311f3e94ce8f297e8',
    messagingSenderId: '524404964921',
    projectId: 'cooking-app-e6531',
    authDomain: 'cooking-app-e6531.firebaseapp.com',
    storageBucket: 'cooking-app-e6531.appspot.com',
    measurementId: 'G-39H59N1Q14',
  );
}
